# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae41804fb06070581ba5f25d3ed6f80ad145cfd2e96226d2c9bd369ad297cb10fc6903d5e146289afdd8dfa9333237872a8b4efff74f7f575a38b7fc68ca49b2

test:
  secret_key_base: 1595e6657f72083dcc933cc1b46db90b8728d1d91d484bb43b74076b868b29b2b1d87e2f533da9ad3a807ecff6d845ad415bf1c4d698a5835d6fe7b1f187165a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
